################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/psock.c \
E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/timer.c \
E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/uip.c \
E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/uip_arp.c 

OBJS += \
./FreeTCPIP/psock.o \
./FreeTCPIP/timer.o \
./FreeTCPIP/uip.o \
./FreeTCPIP/uip_arp.o 

C_DEPS += \
./FreeTCPIP/psock.d \
./FreeTCPIP/timer.d \
./FreeTCPIP/uip.d \
./FreeTCPIP/uip_arp.d 


# Each subdirectory must supply rules for building sources it contributes
FreeTCPIP/psock.o FreeTCPIP/psock.d: E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/psock.c
	@echo 'Scanning and building file: $<'
	@echo 'Invoking: Scanner and Compiler'
	rx-elf-gcc -MM -MP -MF "$(@:%.o=%.d)" -MT "$(@:%.o=%.d)" -nostdinc  -I"E:/Pessoal/Projetos_Pessoal/ProjetosRenesas/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -x c "$<"
	rx-elf-gcc -nostdinc -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -c -x c -o "$(@:%.d=%.o)" "$<"
	@echo 'Finished scanning and building: $<'
	@echo.

FreeTCPIP/timer.o FreeTCPIP/timer.d: E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/timer.c
	@echo 'Scanning and building file: $<'
	@echo 'Invoking: Scanner and Compiler'
	rx-elf-gcc -MM -MP -MF "$(@:%.o=%.d)" -MT "$(@:%.o=%.d)" -nostdinc  -I"E:/Pessoal/Projetos_Pessoal/ProjetosRenesas/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -x c "$<"
	rx-elf-gcc -nostdinc -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -c -x c -o "$(@:%.d=%.o)" "$<"
	@echo 'Finished scanning and building: $<'
	@echo.

FreeTCPIP/uip.o FreeTCPIP/uip.d: E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/uip.c
	@echo 'Scanning and building file: $<'
	@echo 'Invoking: Scanner and Compiler'
	rx-elf-gcc -MM -MP -MF "$(@:%.o=%.d)" -MT "$(@:%.o=%.d)" -nostdinc  -I"E:/Pessoal/Projetos_Pessoal/ProjetosRenesas/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -x c "$<"
	rx-elf-gcc -nostdinc -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -c -x c -o "$(@:%.d=%.o)" "$<"
	@echo 'Finished scanning and building: $<'
	@echo.

FreeTCPIP/uip_arp.o FreeTCPIP/uip_arp.d: E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/Common/ethernet/FreeTCPIP/uip_arp.c
	@echo 'Scanning and building file: $<'
	@echo 'Invoking: Scanner and Compiler'
	rx-elf-gcc -MM -MP -MF "$(@:%.o=%.d)" -MT "$(@:%.o=%.d)" -nostdinc  -I"E:/Pessoal/Projetos_Pessoal/ProjetosRenesas/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -x c "$<"
	rx-elf-gcc -nostdinc -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\..\Source\portable\GCC\RX600" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\include" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\..\..\Common\ethernet\FreeTCPIP" -I"E:/Pessoal/Projetos_Pessoal/FreeRTOS/FreeRTOSV7.4.2/FreeRTOSV7.4.2/FreeRTOS/Demo/RX600_RX62N-RDK_GNURX/RTOSDemo\webserver" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\rx-elf\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\..\rx-elf\lib\gcc\rx-elf\4.5-GNURX_v10.03\optlibinc" -I"C:\Renesas\e2studio\GNURXV~1.03-\rx-elf\rx-elf\optlibinc" -I"E:\Pessoal\Projetos_Pessoal\FreeRTOS\FreeRTOSV7.4.2\FreeRTOSV7.4.2\FreeRTOS\Demo\RX600_RX62N-RDK_GNURX\RTOSDemo\src\sw\FreeRTOS\port" -DDEBUG -g2 -g -mlittle-endian-data -mcpu=rx600 -c -x c -o "$(@:%.d=%.o)" "$<"
	@echo 'Finished scanning and building: $<'
	@echo.

